/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ColorPicker: typeof import('./src/components/ColorPicker.vue')['default']
    copy: typeof import('./src/components/ColorPicker copy.vue')['default']
    IJamBackgroundColor: typeof import('~icons/jam/background-color')['default']
    IPepiconsPopColorPickerCircleFilled: typeof import('~icons/pepicons-pop/color-picker-circle-filled')['default']
    IPhEyedropper: typeof import('~icons/ph/eyedropper')['default']
    IPhEyedropperFill: typeof import('~icons/ph/eyedropper-fill')['default']
    IPhEyedropperSampleFill: typeof import('~icons/ph/eyedropper-sample-fill')['default']
    ISolarBillCheckLineDuotone: typeof import('~icons/solar/bill-check-line-duotone')['default']
    ISolarCheckCircleBold: typeof import('~icons/solar/check-circle-bold')['default']
    ISolarCopyBroken: typeof import('~icons/solar/copy-broken')['default']
    ISolarKeyBoldDuotone: typeof import('~icons/solar/key-bold-duotone')['default']
    ISolarKeyMinimalisticSquareBold: typeof import('~icons/solar/key-minimalistic-square-bold')['default']
    ISolarKeySquareOutline: typeof import('~icons/solar/key-square-outline')['default']
    PasswordGenerator: typeof import('./src/components/PasswordGenerator.vue')['default']
  }
}
